repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-added-large-files
    - id: check-shebang-scripts-are-executable
    - id: check-symlinks
    - id: check-toml
    - id: check-xml
    - id: check-yaml
      args: [ --allow-multiple-documents ]
    - id: end-of-file-fixer
    - id: name-tests-test
      args: [ "--pytest-test-first" ]
      files: ^test/.*\.py$
    - id: trailing-whitespace
      args: [ "--markdown-linebreak-ext=md" ]
