[project]
name = "pycloc"
version = "0.1.0"
description = "Python wrapper for the cloc CLI tool"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = [
    "from-root>=1.3.0",
    "pytest>=8.4.1",
    "pytest-mock>=3.14.1",
    "requests>=2.32.4",
    "ruff>=0.12.2",
    "tqdm>=4.67.1",
    "ty>=0.0.1a14",
]

[tool.hatch.build.targets.sdist]
artifacts = [
    "cloc.ini",
    "cloc.pl",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["."]
addopts = ["--import-mode=importlib"]

[tool.ruff]
line-length = 120

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
