name: Documentation
on:
  push:
    branches: [ main ]
permissions:
  contents: write

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}
      - name: Prepare repository
        uses: ./.github/actions/prepare
      - name: Configure `git` credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Build and deploy website
        run: just deploy
